services:
  prueba-lasso:
    container_name: prueba-lasso
    image: prueba-lasso:latest
    environment:
      - TZ=America/Guayaquil
    ports:
      - 3000:80

    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
