services:
  ventanilla-publica:
    container_name: ventanilla-publica
    image: ventanilla-publica:latest
    environment:
      - TZ=America/Guayaquil
    ports:
      - 3000:80

    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true