@base_url=http://localhost:5000/api

### Get all grants
GET {{base_url}}/grants


### Get grant by id
GET {{base_url}}/grants/2


### Create a new grant
POST {{base_url}}/grants
Content-Type: application/json

[
    {
      "name": "New Grant",
      "description": "This is a new grant."
    },
    {
      "name": "New Grant",
      "description": "This is a new grant."
    }
]

### Delete all grants
DELETE {{base_url}}/grants/clear-all