"""replace grant_name and grant_description with name and description

Revision ID: dd74e2b28a70
Revises: dc9bc80667b2
Create Date: 2025-11-10 21:18:43.677637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd74e2b28a70'
down_revision = 'dc9bc80667b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_constraint(batch_op.f('grants_grant_name_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('grant_description')
        batch_op.drop_column('grant_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('grant_description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('grants_grant_name_key'), ['grant_name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
